"""Synthetic end-to-end backtest for the research vertical slice.

Runs a candidate hedged policy and every FR-005 baseline through the SAME
deterministic engine (same ledger, same fill/cost model, same dataset) and
computes metrics with the shared metrics module. The synthetic dataset is
generated by ``tailhedge.backtest.synthetic`` (seeded, no licensed data).

This module is the single source of truth for the research backtest UI and
the ``/api/v1/backtest/synthetic`` endpoint.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from tailhedge.backtest.baselines import (
    RollingHedgePolicy,
    get_all_baseline_configs,
    run_baseline,
)
from tailhedge.backtest.engine import BacktestConfig
from tailhedge.backtest.metrics import (
    BacktestMetrics,
    BaselineComparison,
    calculate_metrics,
    compare_to_baseline,
)
from tailhedge.backtest.strategy import RollConfig
from tailhedge.backtest.synthetic import generate_synthetic_dataset


@dataclass(frozen=True)
class SyntheticRunEntry:
    """Metrics for one baseline (or the hedged policy) run."""

    name: str
    description: str
    metrics: BacktestMetrics


@dataclass(frozen=True)
class SyntheticBacktestResult:
    """Complete synthetic vertical-slice result."""

    hedged: SyntheticRunEntry
    baselines: list[tuple[SyntheticRunEntry, BaselineComparison]]
    dataset_metadata: dict[str, object]

    def to_api_dict(self) -> dict[str, object]:
        """Serialise for the JSON API endpoint."""

        def _m(metrics: BacktestMetrics) -> dict[str, object]:
            return {
                "cagr": metrics.cagr,
                "max_drawdown": metrics.max_drawdown,
                "max_drawdown_periods": metrics.max_drawdown_periods,
                "total_premium_spent": metrics.total_premium_spent,
                "annualised_premium_spent": metrics.annualised_premium_spent,
                "premium_spend_ratio": metrics.premium_spend_ratio,
                "final_value": metrics.final_value,
                "initial_value": metrics.initial_value,
                "total_return": metrics.total_return,
            }

        return {
            "status": "success",
            "dataset": self.dataset_metadata,
            "hedged": {"name": self.hedged.name, **_m(self.hedged.metrics)},
            "baselines": [
                {
                    "name": entry.name,
                    "metrics": _m(entry.metrics),
                    "cagr_delta": comparison.cagr_delta,
                    "drawdown_improvement": comparison.drawdown_improvement,
                    "tail_efficiency": comparison.tail_efficiency,
                    "fold_utility": comparison.fold_utility,
                }
                for entry, comparison in self.baselines
            ],
        }


def run_synthetic_backtest(
    *,
    trading_days: int = 126,
    seed: int = 20260101,
    initial_cash: float = 100_000.0,
    initial_units: float = 200.0,
    initial_price: float = 500.0,
) -> SyntheticBacktestResult:
    """Run the hedged policy and all baselines through the shared engine.

    Deterministic: the dataset and all runs are seeded/frozen, so repeated
    calls return identical numbers.
    """
    dataset = generate_synthetic_dataset(
        start_date=date(2025, 1, 15),
        trading_days=trading_days,
        seed=seed,
        initial_price=initial_price,
        daily_drift=0.0002,
        daily_vol=0.008,
        crash_start_index=84,
        crash_daily_return=-0.035,
        crash_days=4,
        expiry_interval_days=21,
        option_moneyness=0.95,
    )

    engine_config = BacktestConfig(
        initial_cash=initial_cash,
        initial_units=initial_units,
    )

    # Candidate hedged policy: entry + roll + monetise/reinvest.
    hedged_policy = RollingHedgePolicy(
        roll_config=RollConfig(roll_dte_threshold=7),
        entry_moneyness=0.95,
        entry_target_dte=63,
        budget_pct=0.01,
        monetise_fraction=0.5,
        reinvest_fraction=1.0,
    )
    hedged_metrics = _run_and_score(hedged_policy, engine_config, dataset)

    entries: list[tuple[SyntheticRunEntry, BaselineComparison]] = []
    for spec in get_all_baseline_configs():
        result = run_baseline(
            spec=spec,
            engine_config=engine_config,
            underlying_prices=dataset.underlying_prices,
            quotes_by_day=dataset.quotes_by_day,
            initial_price=initial_price,
        )
        metrics = calculate_metrics(
            result.equity_curve,
            result.premium_events(),
            years=result.years,
        )
        entry = SyntheticRunEntry(
            name=spec.name, description=spec.description, metrics=metrics
        )
        entries.append((entry, compare_to_baseline(hedged_metrics, metrics)))

    return SyntheticBacktestResult(
        hedged=SyntheticRunEntry(
            name="Hedged (roll + monetise)",
            description="Daily policy: 5% OTM put entry, roll at 7 DTE, monetise 50% with reinvestment",
            metrics=hedged_metrics,
        ),
        baselines=entries,
        dataset_metadata=dataset.metadata,
    )


def _run_and_score(
    policy: RollingHedgePolicy,
    engine_config: BacktestConfig,
    dataset: object,
) -> BacktestMetrics:
    """Run a policy through the engine and score it with shared metrics."""
    from tailhedge.backtest.engine import run_daily_backtest

    result = run_daily_backtest(
        config=engine_config,
        policy=policy,
        underlying_prices=dataset.underlying_prices,  # type: ignore[attr-defined]
        quotes_by_day=dataset.quotes_by_day,  # type: ignore[attr-defined]
    )
    return calculate_metrics(
        result.equity_curve,
        result.premium_events(),
        years=result.years,
    )
